source/repos/InvitacionEventos/Controllers/HomeController.cs
using InvitacionEventos.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InvitacionEventos.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Rsvp()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Rsvp(Invitaciones response)
        {
            if (ModelState.IsValid)
            {
                Repository.Add(response);
                return View("Thanks", response);
            }
            else
            {
                return View();
            }
        }
        [ChildActionOnly]
        public ActionResult Attendees()
        {
            return View(Repository.Responses.Where(x => x.Asistira == true));
        }
    }
}

source/repos/InvitacionEventos/Controllers/RsvpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using InvitacionEventos.Models;

namespace InvitacionEventos.Controllers
{
    public class RsvpController : ApiController
    {
        [HttpGet]
        public IEnumerable<Invitaciones> GetAttendees()
        {
            return Repository.Responses.Where(x => x.Asistira == true);
        }
        [HttpPost]
        public void PostResponse(Invitaciones response)
        {
            if (ModelState.IsValid)
            {
                Repository.Add(response);
            }
        }
    }
}

source/repos/InvitacionEventos/Views/Home/Attendees.cshtml
@model IEnumerable<InvitacionEventos.Models.Invitaciones>

@if (Model.Count() == 1)
{
    <p>Has aceptado el evento!</p>
}
else
{
    <p>
        <div class="alert-info">
            Aquí está la lista de personas que asistirán al evento: @string.Join(", ",
Model.Select(x => x.Nombre))
        </div>
    </p>
}

source/repos/InvitacionEventos/Views/Home/Index.cshtml
@{ ViewBag.Title = "Asistencia a eventos";}
<div class="text-center" style="background-color:lightblue">
    <h2>Registra tu asistencia</h2>
    <h3>Te esperamos en los próximos eventos.</h3>
    @Html.ActionLink("Realiza tu petición", "Rsvp", null, new { @class = "btn btn-success" })
</div>

source/repos/InvitacionEventos/Views/Home/Rsvp.cshtml
@model InvitacionEventos.Models.Invitaciones

@{ ViewBag.Title = "Entrada de petición"; }
<link rel="stylesheet" type="text/css" href="~/Content/Site.css" />
<div class="panel panel-primary">
    <div class="panel-heading"><h4>RSVP</h4></div>
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            @Html.ValidationSummary()
            <div class="form-group">
                <label>Tu nombre:</label>
                @Html.TextBoxFor(x => x.Nombre, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Tu correo:</label>
                @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Tu telefono:</label>
                @Html.TextBoxFor(x => x.Telefono, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Asistencia</label>
                @Html.DropDownListFor(x => x.Asistira, new[] {
                new SelectListItem() {Text = "Si, estaré en el evento",
                Value = bool.TrueString},
                new SelectListItem() {Text = "No, no podré asistir",
                Value = bool.FalseString}
                }, "Elige una opcion", new { @class = "form-control" })
            </div>
            <div class="text-center">
                <input class="btn btn-success" type="submit" value="Enviar petición" />
            </div>
        }
    </div>
</div>

source/repos/InvitacionEventos/Views/Home/Thanks.cshtml
@model InvitacionEventos.Models.Invitaciones

@{ ViewBag.Title = "Conformidad";}
<h1>Gracias, @Model.Nombre!</h1>
<div class="panel-body">
    @if (Model.Asistira == true)
    {
        <div class="alert-success">Gracias por tu disposición, te esperamos</div>
        @Html.Action("Attendees", "Home")
    }
    else
    {
        <div class="alert-danger">Sentimos no poder contar contigo en esta ocasión,te esperamos en próximos eventos</div>
    }
</div>
<div class="btn-link" style="border-bottom-style:double">@Html.ActionLink("Regresar al inicio", "Index")</div>